apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: preview-health-check
spec:

  metrics:

  - name: health

    successCondition: result == "200"

    provider:
      web:
        url: http://rollout-demo-preview/
