apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: experiment-version-check
  namespace: demo
spec:
  metrics:
    - name: version-check
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: check-version
                    image: curlimages/curl:8.10.1
                    command:
                      - sh
                      - -c
                      - |
                        echo "Running experiment analysis"
                        exit 0