apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hpa-demo
  namespace: demo
spec:
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
        - name: hpa-demo
          image: registry.k8s.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
  strategy:
    canary:
      canaryService: hpa-demo-canary
      stableService: hpa-demo-stable
      trafficRouting:
        istio:
          virtualService:
            name: hpa-demo-vsvc
            routes:
              - primary
      steps:
        - setWeight: 20
        - setCanaryScale:
            replicas: 1        # exactly 1 canary pod gets 20% of traffic
        - pause: { }
        - setWeight: 50
        - setCanaryScale:
            replicas: 3
        - pause: { }
        - setWeight: 100
