apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: demo
spec:
  replicas: 5
  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: rollouts-demo

  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:green
          ports:
            - containerPort: 8080

  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: rollouts-demo-vsvc
            routes:
              - primary
          destinationRule:
            name: rollouts-demo-destrule
            canarySubsetName: canary
            stableSubsetName: stable

      steps:
        - setWeight: 20

        - experiment:
            duration: 2m

            templates:
              - name: baseline
                specRef: stable

              - name: canary
                specRef: canary

            analyses:
              - name: success-rate
                requiredForCompletion: true
                templateName: success-rate
                args:
                  - name: service-name
                    value: rollouts-demo

        - setWeight: 50

        - pause:
            duration: 10s

        - setWeight: 100
